// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfbsptlqcbfvdxqkqemk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYnNwdGxxY2JmdmR4cWtxZW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NDgyODEsImV4cCI6MjA1MzMyNDI4MX0.htCQco1OBAVKCDOkpJ8LVJWUmCfZ7vn32l_fPUYh3YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);